### ISSUE TITLE
Module not installable by composer

### ISSUE THREAD

**Issue by juagarc4** [NewZeal/message_thread#1]
Hello, 

I'm really interested in this module. But it can't be installed with 
"composer require drupal/message_thread."

I receive the message: 

> [InvalidArgumentException]                                                                                                                          
>   Could not find package drupal/message_thread at any version for your minimum-stability (dev). Check the package spelling or your minimum-stability

Could you make it installable by composer?

Thank you in advance.

**Comment by NewZeal** [comment]
That's because there was no version of the module on Drupal.  There is now.

**Comment by juagarc4** [comment]
Hi, 
It worked fine. 
Thank you very much.
